import { Shadows_Into_Light } from 'next/font/google'
import './globals.css'

const shadow = Shadows_Into_Light({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={shadow.className}>{children}</body>
    </html>
  )
}
